summaryLength: 300
baseURL = "https://github.com/ragloria-bot/4303-ramona-gloria-portfolio-2026"
locale = 'en-us'
title = 'Ramona Gloria | Bridging Design & Development'
staticDir = ["assets_static"]
theme = "PaperMod"
[params.profileMode]
    enabled = true
    title = "Ramona Gloria"
    subtitle = """
**Texas Tech University Student | Computer Applications** <br><br>  
Designing for the user, developing for the future. I'm Ramona Gloria,  
a student developer passionate about crafting pixel-perfect interfaces  
and robust, scalable, and secure backend systems.
"""
    imageUrl = "images/RamonaGloria-TTU Card.jpg" # Place this image in your static/images/ folder
    imageWidth = 250
    imageHeight = 300
    [[params.profileMode.buttons]]
        name = "Projects"
        url = "projects"
    [[params.profileMode.buttons]]
        name = "Resume PDF"
        url = "resume.pdf"
    [menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/" 
    weight = 20
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 30
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    weight = 40
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50
  [markup.goldmark.renderer]
    unsafe = true


  
    
