baseURL = "https://github.com/ragloria-bot/4303-ramona-gloria-portfolio-2026"
locale = 'en-us'
title = 'My New Hugo Project'
staticDir = ["assets_static"]
theme = "PaperMod"
[params.profileMode]
    enabled = true
    title = "Ramona Gloria"
    subtitle = "Texas Tech University Student | Computer Applications"
    imageUrl = "images/RamonaGloria-TTU Card.jpg" # Place this image in your static/images/ folder
    imageWidth = 120
    imageHeight = 120
    [[params.profileMode.buttons]]
        name = "Projects"
        url = "projects"
    [[params.profileMode.buttons]]
        name = "Resume"
        url = "resume.pdf"
    [menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 30
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20